### ISSUE TITLE
image is broken in 3.6

### ISSUE THREAD

**Issue by zak-hassan** [radanalyticsio/pyspark-s3-notebook#2]
The python notebook doesn't show up in the image. 

Version: 3.6

Error Msg:

See attached log file
[base-notebook-1-s5jhz.log](https://github.com/radanalyticsio/pyspark-s3-notebook/files/1616286/base-notebook-1-s5jhz.log)

**Comment by zak-hassan** [comment]
```bash

oc new-app radanalyticsio/base-notebook \
   -e JUPYTER_NOTEBOOK_PASSWORD=supersecret \
   -e JUPYTER_NOTEBOOK_X_INCLUDE=https://radanalytics.io/assets/s3-source-example/s3-source-example.ipynb
oc expose svc/base-notebook
```

**Comment by zak-hassan** [comment]
@elmiko Do you know if the base notebook may be broken?

**Comment by elmiko** [comment]
not that i am aware of, but i'm running this against a local cluster to confirm your results

**Comment by elmiko** [comment]
@zmhassan i am having trouble confirming this

i tested the command you provided against the following cluster:
```
$ oc version
oc v3.7.0+bfd1f00-9
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://shift.opb.studios:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```
and was able to run the notebook through to the end

from the logs, it looks like your notebook was not able to get a connection to radanalytics.io:
```
curl: (7) Failed connect to radanalytics.io:443; Connection timed out                                                                               
```
i wonder if there was a connection issue from the machine you were running the container on?

**Comment by elmiko** [comment]
i realized i had a version mismatch against the server, i updated my tests against this:
```
$ oc version
oc v3.7.0+bfd1f00-9
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://shift.opb.studios:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
```

everything still worked for me

**Comment by zak-hassan** [comment]
oc checkout v3.6.0
Try to run it with that version and you'll see what I saw

```bash
[zhassan@analytics origin]$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://10.15.17.99:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

```

**Comment by elmiko** [comment]
just tried with this:

```
$ oc version
oc v3.7.0+bfd1f00-9
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://shift.opb.studios:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

everything is still working.

given the output in your log file, i think the machine your notebook pod was scheduled on was not able to access radanaltyics.io. is this problem still persisting?

**Comment by zak-hassan** [comment]
Everything is working. I had a network issue.
